# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('username', models.CharField(db_index=True, help_text='Username attempted for login.', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('locked', 'Account Locked')], db_index=True, help_text='Status of the login attempt.', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the login attempt.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request.', null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for login failure (e.g., invalid password, account locked).', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'db_table': 'login_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('token_jti', models.CharField(db_index=True, help_text='JWT JTI claim of the blacklisted token.', max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the token was blacklisted.')),
                ('reason', models.CharField(blank=True, help_text='Reason for blacklisting (logout, disable, delete, etc.).', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the token was blacklisted.', null=True)),
            ],
            options={
                'verbose_name': 'Token Blacklist Metadata',
                'verbose_name_plural': 'Token Blacklist Metadata',
                'db_table': 'token_blacklist_metadata',
                'ordering': ['-blacklisted_at'],
            },
        ),
    ]
