# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with the login attempt (if found).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenblacklistmetadata',
            name='user',
            field=models.ForeignKey(help_text='User who owned the blacklisted token.', on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', 'status', 'created_at'], name='login_attem_usernam_46363e_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['user', 'created_at'], name='login_attem_user_id_18b2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='login_attem_ip_addr_f68fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklistmetadata',
            index=models.Index(fields=['user', 'blacklisted_at'], name='token_black_user_id_6f08ef_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklistmetadata',
            index=models.Index(fields=['token_jti'], name='token_black_token_j_63f98e_idx'),
        ),
    ]
