# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('notification_type', models.CharField(choices=[('payment', 'Payment Notification'), ('transaction', 'Transaction Notification'), ('user_management', 'User Management Notification'), ('password_reset', 'Password Reset Notification'), ('system', 'System Notification'), ('audit', 'Audit Notification'), ('alert', 'Alert')], db_index=True, help_text='Type of notification.', max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', help_text='Severity level of the notification.', max_length=10)),
                ('title', models.CharField(help_text='Notification title.', max_length=200)),
                ('message', models.TextField(help_text='Notification message content.')),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'Transaction', 'User').", max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object.', null=True)),
                ('related_object_reference', models.CharField(blank=True, help_text='Reference code of the related object.', max_length=100, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read.')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when notification was read.', null=True)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been dismissed.')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was dismissed.', null=True)),
                ('delivered_via_websocket', models.BooleanField(default=False, help_text='Whether notification was delivered via WebSocket.')),
                ('websocket_delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when WebSocket delivery occurred.', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional notification data (e.g., transaction details).')),
                ('action_url', models.CharField(blank=True, help_text='URL for notification action (optional).', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('channel_name', models.CharField(db_index=True, help_text='Channels channel name for this connection.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the WebSocket connection.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the connection.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the connection is currently active.')),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='Timestamp when the connection was disconnected.', null=True)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now, help_text='Last heartbeat timestamp for connection health monitoring.')),
            ],
            options={
                'verbose_name': 'WebSocket Connection',
                'verbose_name_plural': 'WebSocket Connections',
                'db_table': 'websocket_connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
