# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='User who should receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websocketconnection',
            name='user',
            field=models.ForeignKey(help_text='User associated with this WebSocket connection.', on_delete=django.db.models.deletion.CASCADE, related_name='websocket_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['severity', 'created_at'], name='notificatio_severit_5abb00_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='notificatio_is_read_9b69ad_idx'),
        ),
        migrations.AddIndex(
            model_name='websocketconnection',
            index=models.Index(fields=['user', 'is_active'], name='websocket_c_user_id_0bac24_idx'),
        ),
        migrations.AddIndex(
            model_name='websocketconnection',
            index=models.Index(fields=['channel_name'], name='websocket_c_channel_88537f_idx'),
        ),
        migrations.AddIndex(
            model_name='websocketconnection',
            index=models.Index(fields=['last_heartbeat'], name='websocket_c_last_he_b91f6f_idx'),
        ),
    ]
