# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mpesa', 'Mpesa Daraja'), ('paystack', 'Paystack')], help_text='Payment provider name.', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is active.')),
                ('config', models.JSONField(default=dict, help_text='Provider-specific configuration (encrypted in production).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last configuration update timestamp.')),
            ],
            options={
                'verbose_name': 'Payment Provider Configuration',
                'verbose_name_plural': 'Payment Provider Configurations',
                'db_table': 'payment_provider_config',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means the record is logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('reference', models.CharField(db_index=True, help_text='Internal transaction reference (e.g., DP5TG20VG1)', max_length=20, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text="Payment provider's reference code (Mpesa MerchantRequestID or Paystack reference)", max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in KES.', max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('paystack', 'Paystack')], db_index=True, help_text='Payment method used.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Transaction status.', max_length=10)),
                ('mpesa_phone_number', models.CharField(blank=True, help_text='Phone number for Mpesa transactions.', max_length=15, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, db_index=True, help_text='Mpesa CheckoutRequestID from STK Push.', max_length=100, null=True)),
                ('mpesa_response_description', models.TextField(blank=True, help_text='Mpesa response description or failure reason.', null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='Mpesa transaction receipt number (upon completion).', max_length=50, null=True)),
                ('paystack_access_code', models.CharField(blank=True, help_text='Paystack access code for redirect checkout.', max_length=100, null=True)),
                ('paystack_authorization_url', models.URLField(blank=True, help_text='Paystack authorization URL for redirect checkout.', null=True)),
                ('description', models.TextField(blank=True, help_text='Transaction description or purpose.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata.')),
                ('callback_received_at', models.DateTimeField(blank=True, help_text='Timestamp when callback/webhook was received.', null=True)),
                ('callback_payload', models.JSONField(blank=True, default=dict, help_text='Raw callback/webhook payload for audit.')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
