# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('action', models.CharField(choices=[('create', 'Create'), ('modify_attempted', 'Modify Attempted'), ('delete_attempted', 'Delete Attempted'), ('view', 'View'), ('export', 'Export')], db_index=True, help_text='Action performed.', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which action was performed.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request.', null=True)),
            ],
            options={
                'verbose_name': 'Ledger Audit Log',
                'verbose_name_plural': 'Ledger Audit Logs',
                'db_table': 'ledger_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in KES.', max_digits=12)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, help_text='Type of ledger entry (credit/debit).', max_length=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Running balance after this entry.', max_digits=12)),
                ('description', models.TextField(help_text='Description of the ledger entry.')),
                ('reference', models.CharField(db_index=True, help_text='Unique reference for this ledger entry.', max_length=50, unique=True)),
                ('source', models.CharField(choices=[('mpesa', 'Mpesa'), ('paystack', 'Paystack'), ('manual', 'Manual Adjustment'), ('refund', 'Refund'), ('system', 'System')], default='system', help_text='Source of the ledger entry.', max_length=20)),
                ('is_finalized', models.BooleanField(default=True, help_text='Once True, entry cannot be modified (always True for ledger entries).')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which entry was created.', null=True)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
