# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerauditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User or system that created this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Linked transaction (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='user',
            field=models.ForeignKey(help_text='User associated with this ledger entry.', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerauditlog',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, help_text='Ledger entry associated with this audit log.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ledger.ledgerentry'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['user', 'created_at'], name='ledger_entr_user_id_b2381a_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type', 'created_at'], name='ledger_entr_entry_t_bfe8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction', 'created_at'], name='ledger_entr_transac_060c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reference'], name='ledger_entr_referen_4aa8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['source', 'created_at'], name='ledger_entr_source_013ef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_ledger_amount'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='non_negative_balance'),
        ),
        migrations.AddIndex(
            model_name='ledgerauditlog',
            index=models.Index(fields=['action', 'created_at'], name='ledger_audi_action_15bccf_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerauditlog',
            index=models.Index(fields=['user', 'created_at'], name='ledger_audi_user_id_d65567_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerauditlog',
            index=models.Index(fields=['ledger_entry', 'created_at'], name='ledger_audi_ledger__04d0d3_idx'),
        ),
    ]
