# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means the record is logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('username', models.CharField(db_index=True, help_text='Unique username for login.', max_length=50, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address for notifications and password reset.', max_length=254, unique=True)),
                ('first_name', models.CharField(help_text="User's first name.", max_length=50)),
                ('last_name', models.CharField(help_text="User's last name.", max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=15, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff Member')], db_index=True, default='staff', help_text='User role: admin or staff.', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user should be treated as active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether this user has all permissions.')),
                ('temporary_password', models.CharField(blank=True, help_text='Stores temporary password until changed.', max_length=128, null=True)),
                ('must_change_password', models.BooleanField(default=False, help_text='Force password change on next login.')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Timestamp when password was last changed.', null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Count of consecutive failed login attempts.')),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, help_text='Account lockout expiry timestamp.', null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, help_text='Last time the user was active in the system.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Status of the password reset request.', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason provided for the password reset request.', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes when approving or rejecting.', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was processed.', null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reset_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who requested the password reset.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'db_table': 'password_reset_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['locked_until'], name='users_locked__615cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_seen'], name='users_last_se_f59089_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['user', 'status'], name='password_re_user_id_a8b61d_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['status', 'created_at'], name='password_re_status_bfba9d_idx'),
        ),
    ]
