# Generated by Django 6.0.3 on 2026-03-08 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_approved', 'Password Reset Approved'), ('password_reset_rejected', 'Password Reset Rejected'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('transaction_initiated', 'Transaction Initiated'), ('transaction_completed', 'Transaction Completed'), ('transaction_failed', 'Transaction Failed'), ('payment_initiated', 'Payment Initiated'), ('payment_callback', 'Payment Callback'), ('payment_webhook', 'Payment Webhook'), ('ledger_entry_created', 'Ledger Entry Created'), ('profile_updated', 'Profile Updated'), ('token_blacklisted', 'Token Blacklisted'), ('token_refreshed', 'Token Refreshed'), ('session_expired', 'Session Expired'), ('permission_denied', 'Permission Denied'), ('api_request', 'API Request'), ('websocket_connected', 'WebSocket Connected'), ('websocket_disconnected', 'WebSocket Disconnected'), ('system_event', 'System Event'), ('config_changed', 'Configuration Changed'), ('export_data', 'Data Exported'), ('integrity_check', 'Integrity Check'), ('other', 'Other')], db_index=True, help_text='Type of action performed.', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', help_text='Severity level of the action.', max_length=10)),
                ('category', models.CharField(db_index=True, help_text='Category of the action (authentication, payment, user_management, etc.).', max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the action.')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action.')),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'Transaction', 'User').", max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object.', null=True)),
                ('related_object_reference', models.CharField(blank=True, db_index=True, help_text='Reference code of the related object (e.g., transaction reference).', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request.', null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.).', max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, help_text='Request path/endpoint.', max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier.', max_length=100, null=True)),
                ('server_hostname', models.CharField(blank=True, help_text='Server hostname where action was processed.', max_length=100, null=True)),
                ('is_finalized', models.BooleanField(default=True, help_text='Once True, entry cannot be modified (always True for audit logs).')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.')),
                ('session_key', models.CharField(db_index=True, help_text='Session key identifier.', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the session.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the session is currently active.')),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Last activity timestamp for this session.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Session expiration timestamp.', null=True)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
